"""The scorecard as a PDF the candidate can keep.

Deliberately not a screenshot of the web page. The web page is a working
surface; this is the artefact that leaves the application, so it is laid out for
print: one column, a fixed measure, and the provenance footer that lets anyone
reading it see which prompt versions produced the numbers.

The design follows the same rule as the interface — colour means judgement.
Every rule, bar and figure here is grey except the ones expressing a verdict.
"""

import logging
from datetime import datetime
from pathlib import Path

from fpdf import FPDF
from sqlmodel import Session

from app.exceptions import StageNotReady
from app.models import EvidenceStatus, InterviewSession, MatchItem, Scorecard
from app.services.analysis import get_report
from app.services.scorecard import get_scorecard

logger = logging.getLogger("cvcoach.pdf")

# --- the product palette, as RGB -------------------------------------------
# Mirrors the tokens in frontend/src/styles.css. Kept in sync by hand: the two
# renderers cannot share a stylesheet, and a scorecard whose verdict colours
# disagree with the screen it was exported from is worse than either alone.
INK = (19, 26, 25)
INK_2 = (69, 81, 79)
INK_3 = (101, 111, 109)
RULE = (201, 210, 208)
PAPER_2 = (247, 249, 248)
VERDICT = {
    "strong": (44, 106, 74),
    "partial": (144, 101, 22),
    "missing": (158, 51, 36),
}
VERDICT_COPY = {"strong": "Evidenced", "partial": "Thin", "missing": "No evidence"}

FONT_DIR = Path(__file__).resolve().parent.parent / "assets" / "fonts"

# Helvetica is Latin-1. The application emits typographic punctuation, so these
# are mapped to their ASCII equivalents rather than lost. See assets/fonts/README.
_SANITISE = str.maketrans({
    "—": "-", "–": "-", "−": "-",
    "‘": "'", "’": "'", "‚": ",",
    "“": '"', "”": '"',
    "…": "...", "•": "-", "·": "-",
    "→": "->", "←": "<-",
    " ": " ", "​": "",
    "‹": "<", "›": ">", "«": '"', "»": '"',
})


def _tone(score: int, max_score: int = 100) -> str:
    """The same three-step scale the interface uses, so a colour means one thing."""
    pct = (score / max_score) * 100 if max_score else 0
    if pct >= 70:
        return "strong"
    if pct >= 45:
        return "partial"
    return "missing"


class Scoresheet(FPDF):
    """Page furniture: the mark, the running head and the footer."""

    def __init__(self, title: str, unicode_ok: bool) -> None:
        super().__init__(orientation="P", unit="mm", format="A4")
        self.doc_title = title
        self.sans = "DejaVu" if unicode_ok else "Helvetica"
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(20, 18, 20)

    def clean(self, text: str) -> str:
        text = (text or "").translate(_SANITISE)
        if self.sans == "DejaVu":
            return text
        # Anything still outside Latin-1 would raise at render time.
        return text.encode("latin-1", "replace").decode("latin-1")

    def header(self) -> None:
        # The mark: the verdict rule beside two quoted lines, same as the app icon.
        x, y = 20, 11
        self.set_fill_color(*VERDICT["strong"])
        self.rect(x, y, 1.2, 6.5, style="F")
        self.set_fill_color(*INK)
        self.rect(x + 3, y + 0.6, 6.5, 1.1, style="F")
        self.rect(x + 3, y + 2.9, 6.5, 1.1, style="F")
        self.set_fill_color(*INK_3)
        self.rect(x + 3, y + 5.2, 4, 1.1, style="F")

        self.set_xy(x + 12, y + 1)
        self.set_font(self.sans, "B", 7.5)
        self.set_text_color(*INK_3)
        self.cell(60, 4, "INTERVIEW COACH", align="L")

        self.set_xy(-80, y + 1)
        self.set_font(self.sans, "", 7.5)
        self.cell(60, 4, self.clean(self.doc_title)[:46], align="R")

        self.set_draw_color(*RULE)
        self.set_line_width(0.2)
        self.line(20, 22, 190, 22)
        self.set_y(30)

    def footer(self) -> None:
        self.set_y(-14)
        self.set_draw_color(*RULE)
        self.line(20, self.get_y() - 2, 190, self.get_y() - 2)
        self.set_font(self.sans, "", 7)
        self.set_text_color(*INK_3)
        self.cell(
            0, 4,
            self.clean(
                "Every verdict in this report cites the sentence it was drawn from. "
                "Generated by AI Interview Coach."
            ),
            align="L",
        )
        self.set_y(-14)
        self.cell(0, 4, f"{self.page_no()}", align="R")

    # --- building blocks ---------------------------------------------------
    def kicker(self, text: str) -> None:
        self.set_font(self.sans, "B", 7)
        self.set_text_color(*INK_3)
        self.cell(0, 4, self.clean(text.upper()), new_x="LMARGIN", new_y="NEXT")
        self.ln(1.5)

    def body(self, text: str, size: float = 9.5, colour: tuple = INK_2) -> None:
        self.set_font(self.sans, "", size)
        self.set_text_color(*colour)
        self.multi_cell(0, 4.6, self.clean(text), new_x="LMARGIN", new_y="NEXT")

    def rule(self, gap: float = 4) -> None:
        self.ln(gap)
        self.set_draw_color(*RULE)
        self.line(20, self.get_y(), 190, self.get_y())
        self.ln(gap)

    def bar(self, label: str, value: float, maximum: float, tone: str) -> None:
        self.set_font(self.sans, "", 8.5)
        self.set_text_color(*INK_2)
        self.cell(70, 4.4, self.clean(label))
        self.set_font(self.sans, "B", 8.5)
        self.set_text_color(*VERDICT[tone])
        self.cell(18, 4.4, f"{value:.1f} / {maximum:g}", align="R")

        x, y = 112, self.get_y() + 1.4
        width = 78
        self.set_fill_color(*RULE)
        self.rect(x, y, width, 1.8, style="F")
        self.set_fill_color(*VERDICT[tone])
        self.rect(x, y, max(0.6, width * min(1.0, value / maximum)), 1.8, style="F")
        self.ln(6)

    def quoted(self, quote: str, source: str, tone: str) -> None:
        """The evidence line: a marked-up quote with the verdict rule beside it."""
        self.set_font(self.sans, "I", 8.5)
        self.set_text_color(*INK_2)
        top = self.get_y()
        self.set_x(26)
        self.multi_cell(158, 4.2, self.clean(f'"{quote}"'), new_x="LMARGIN", new_y="NEXT")
        bottom = self.get_y()

        self.set_fill_color(*VERDICT[tone])
        self.rect(22.5, top + 0.4, 0.9, max(3.0, bottom - top - 1.2), style="F")

        if source:
            self.set_x(26)
            self.set_font(self.sans, "", 6.8)
            self.set_text_color(*INK_3)
            self.cell(0, 3.4, self.clean(source.upper()), new_x="LMARGIN", new_y="NEXT")
        self.ln(1.5)


def _register_unicode(pdf: Scoresheet) -> bool:
    regular = FONT_DIR / "DejaVuSans.ttf"
    bold = FONT_DIR / "DejaVuSans-Bold.ttf"
    if not regular.exists():
        return False
    pdf.add_font("DejaVu", "", str(regular))
    pdf.add_font("DejaVu", "B", str(bold if bold.exists() else regular))
    pdf.add_font("DejaVu", "I", str(regular))
    return True


def build(session: InterviewSession, db: Session) -> bytes:
    card: Scorecard | None = get_scorecard(session.id or 0, db)
    if card is None:
        raise StageNotReady("Build the scorecard before exporting it.")
    report, items = get_report(session.id or 0, db)

    # add_font has to happen on the instance before the first page triggers header().
    pdf = Scoresheet(session.title, unicode_ok=False)
    if _register_unicode(pdf):
        pdf.sans = "DejaVu"
    pdf.add_page()

    # --- headline ----------------------------------------------------------
    pdf.set_font(pdf.sans, "B", 21)
    pdf.set_text_color(*INK)
    pdf.multi_cell(0, 8.5, pdf.clean(session.title), new_x="LMARGIN", new_y="NEXT")
    if session.target_role:
        pdf.set_font(pdf.sans, "", 10)
        pdf.set_text_color(*INK_3)
        pdf.cell(0, 5, pdf.clean(session.target_role), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    tone = _tone(card.readiness_score)
    pdf.set_font(pdf.sans, "B", 44)
    pdf.set_text_color(*VERDICT[tone])
    pdf.cell(34, 16, str(card.readiness_score))
    pdf.set_font(pdf.sans, "", 11)
    pdf.set_text_color(*INK_3)
    pdf.cell(0, 16, pdf.clean(f"/ 100   {card.readiness_band}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    if card.summary:
        pdf.body(card.summary, size=10)
    pdf.rule()

    # --- competencies ------------------------------------------------------
    competencies = card.competencies
    if competencies:
        pdf.kicker("Competencies")
        for name, value in sorted(competencies.items(), key=lambda kv: kv[1]):
            pdf.bar(name, float(value), 5, _tone(float(value), 5))
        pdf.set_font(pdf.sans, "", 7.5)
        pdf.set_text_color(*INK_3)
        pdf.cell(0, 4, "Averaged across every scored answer, weakest first.",
                 new_x="LMARGIN", new_y="NEXT")
        pdf.rule()

    # --- strengths and gaps ------------------------------------------------
    for kicker, entries in (("Strengths", card.strengths), ("Gaps", card.gaps)):
        if not entries:
            continue
        pdf.kicker(kicker)
        for entry in entries:
            pdf.set_font(pdf.sans, "", 9.5)
            pdf.set_text_color(*INK_2)
            pdf.set_x(20)
            pdf.cell(4, 4.6, "-")
            pdf.multi_cell(166, 4.6, pdf.clean(entry), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
    pdf.rule(3)

    # --- the evidence table ------------------------------------------------
    if report is not None and items:
        pdf.kicker("Requirement by requirement")
        pdf.set_font(pdf.sans, "", 8)
        pdf.set_text_color(*INK_3)
        pdf.multi_cell(
            0, 4,
            pdf.clean(
                f"CV match {report.overall_score}/100. Behavioural requirements are "
                f"listed but excluded from that score: no CV can evidence them."
            ),
            new_x="LMARGIN", new_y="NEXT",
        )
        pdf.ln(3)

        for item in items:
            status = item.status.value if hasattr(item.status, "value") else str(item.status)
            if pdf.get_y() > 245:
                pdf.add_page()

            # The chip belongs on the requirement's FIRST line, so the top of the
            # block is captured before the text wraps rather than after.
            top = pdf.get_y()
            pdf.set_font(pdf.sans, "B", 9.5)
            pdf.set_text_color(*INK)
            pdf.multi_cell(138, 4.8, pdf.clean(item.requirement))
            after = pdf.get_y()

            pdf.set_xy(158, top)
            pdf.set_font(pdf.sans, "B", 7)
            pdf.set_text_color(*VERDICT[status])
            pdf.cell(32, 4.8, VERDICT_COPY[status].upper(), align="R")
            pdf.set_xy(20, after + 0.8)

            if item.evidence_quote:
                source = " . ".join(
                    x for x in ["CV", item.evidence_section or "", 
                                f"p.{item.evidence_page}" if item.evidence_page else ""]
                    if x
                )
                pdf.quoted(item.evidence_quote, source, status)
            else:
                pdf.set_x(26)
                pdf.set_font(pdf.sans, "", 8.5)
                pdf.set_text_color(*INK_3)
                pdf.cell(0, 4.4, "No sentence in the CV supports this.",
                         new_x="LMARGIN", new_y="NEXT")
                pdf.ln(1.5)

    # --- what to do next ---------------------------------------------------
    actions = card.action_items
    if actions:
        if pdf.get_y() > 210:
            pdf.add_page()
        else:
            pdf.rule()
        pdf.kicker("Do this next")
        for action in actions:
            if pdf.get_y() > 250:
                pdf.add_page()
            priority = action.get("priority", "medium")
            chip = {"high": "missing", "medium": "partial", "low": "strong"}[priority]
            pdf.set_font(pdf.sans, "B", 7)
            pdf.set_text_color(*VERDICT[chip])
            pdf.cell(18, 4.6, priority.upper())
            pdf.set_font(pdf.sans, "B", 10)
            pdf.set_text_color(*INK)
            pdf.multi_cell(152, 4.6, pdf.clean(action.get("title", "")),
                           new_x="LMARGIN", new_y="NEXT")
            for prefix, key in (("", "why"), ("How: ", "how")):
                if action.get(key):
                    pdf.set_x(38)
                    pdf.set_font(pdf.sans, "", 8.5)
                    pdf.set_text_color(*INK_2)
                    pdf.multi_cell(152, 4.2, pdf.clean(prefix + action[key]),
                                   new_x="LMARGIN", new_y="NEXT")
            pdf.ln(2.5)

    # --- provenance --------------------------------------------------------
    pdf.rule(3)
    pdf.set_font(pdf.sans, "", 7)
    pdf.set_text_color(*INK_3)
    stamp = datetime.now().strftime("%d %B %Y, %H:%M")
    versions = ", ".join(
        v for v in [report.prompt_version if report else "", card.prompt_version] if v
    )
    pdf.multi_cell(
        0, 3.6,
        pdf.clean(f"Generated {stamp}. Prompt versions: {versions or 'n/a'}."),
        new_x="LMARGIN", new_y="NEXT",
    )

    return bytes(pdf.output())


def filename_for(session: InterviewSession) -> str:
    safe = "".join(c if c.isalnum() or c in " -_" else "" for c in session.title).strip()
    return f"{(safe or 'scorecard').replace(' ', '-')}-scorecard.pdf"
