import { useEffect, useState } from "react";
import { Link, useOutletContext } from "react-router-dom";

import { api, ApiError } from "../api/client";
import type { MatchReport, SessionOut } from "../api/types";
import {
  Chip, ErrorBox, EvidenceLine, Gauge, Head, Row, Spinner, Verdict,
} from "../components/bits";

interface Ctx { session: SessionOut | null; refresh: () => Promise<void> }

export function Report() {
  const { session, refresh } = useOutletContext<Ctx>();
  const [report, setReport] = useState<MatchReport | null>(null);
  const [error, setError] = useState<unknown>(null);
  const [busy, setBusy] = useState(false);
  const [missing, setMissing] = useState(false);

  useEffect(() => {
    if (!session) return;
    api.getAnalysis(session.id)
      .then(setReport)
      .catch((err) => {
        if (err instanceof ApiError && err.status === 404) setMissing(true);
        else setError(err);
      });
  }, [session?.id]);

  async function run() {
    if (!session) return;
    setBusy(true);
    setError(null);
    try {
      setReport(await api.runAnalysis(session.id));
      setMissing(false);
      await refresh();
    } catch (err) {
      setError(err);
    } finally {
      setBusy(false);
    }
  }

  if (missing) {
    return (
      <div className="sheet">
        <Head margin={<span className="label">Stage 1</span>}>
          <h1 className="display h1">Gap analysis</h1>
          <p className="prose">No analysis has been run for this session yet.</p>
          <ErrorBox error={error} />
          <div className="split">
            <button className="btn" onClick={run} disabled={busy}>
              {busy ? "Analysing…" : "Run gap analysis"}
            </button>
            <Link className="btn btn--ghost" to={`/session/${session?.id}/upload`}>
              Check documents
            </Link>
          </div>
        </Head>
      </div>
    );
  }

  if (!report) {
    return <div className="sheet"><Spinner label="Loading analysis…" /></div>;
  }

  const counts = report.counts ?? {};
  const behavioural = report.items.filter((i) => i.kind === "behavioural");

  return (
    <div className="sheet">
      <Head margin={<span className="label">Stage 1</span>}>
        <h1 className="display h1">Gap analysis</h1>
        <Gauge value={report.overall_score} />
        <p className="label" style={{ marginTop: "0.2rem" }}>{report.verdict}</p>
        <p className="prose" style={{ marginTop: "1rem" }}>{report.summary}</p>
        <div className="split" style={{ marginTop: "0.9rem" }}>
          <Chip tone="strong">{counts.strong ?? 0} evidenced</Chip>
          <Chip tone="partial">{counts.partial ?? 0} thin</Chip>
          <Chip tone="missing">{counts.missing ?? 0} missing</Chip>
        </div>
        <ErrorBox error={error} />
      </Head>

      {report.items.filter((i) => i.kind !== "behavioural").map((item) => (
        <Row
          key={item.id}
          margin={
            <>
              <Verdict status={item.status} />
              <span className="label">
                {item.category === "must_have" ? "Must have" : "Nice to have"}
              </span>
            </>
          }
        >
          <h2 className="display h3">{item.requirement}</h2>
          <p className="prose" style={{ margin: "0.4rem 0 0", fontSize: "0.89rem" }}>
            {item.reasoning}
          </p>
          <EvidenceLine
            quote={item.evidence_quote}
            page={item.evidence_page}
            section={item.evidence_section}
            status={item.status}
          />
        </Row>
      ))}

      {/* Requirements no CV can evidence. Scoring them would mark the candidate
          down for a limitation of the medium, so they are shown apart and
          carry no verdict — they become interview questions instead. */}
      {behavioural.length ? (
        <Row margin={<span className="label">Not on a CV</span>}>
          <h2 className="display h3">Asked about in the interview</h2>
          <p className="prose" style={{ margin: "0.4rem 0 0.9rem", fontSize: "0.89rem" }}>
            The posting asks for {behavioural.length === 1 ? "this" : "these"} too. No CV
            can show {behavioural.length === 1 ? "it" : "them"}, so {behavioural.length === 1
            ? "it is" : "they are"} left out of the score and turned into practice questions.
          </p>
          <ul className="list list--bullet">
            {behavioural.map((i) => <li key={i.id}>{i.requirement}</li>)}
          </ul>
        </Row>
      ) : null}

      <Row margin={<span className="label">Next</span>}>
        <p className="prose">
          The questions are built from this table: the requirements with no evidence come
          first, because those are the ones that end interviews.
        </p>
        <Link className="btn" to={`/session/${session?.id}/room`}>
          Go to practice
        </Link>
        <p className="hint" style={{ marginTop: "0.8rem" }}>
          Generated by prompt <code>{report.prompt_version}</code>.
        </p>
      </Row>
    </div>
  );
}
